services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=medium'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=rinor'
    ports:
      - '5432:5432'
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mysqlmedium'
      - 'MYSQL_ROOT_PASSWORD=rootpassword'
      - 'MYSQL_USER=user'
      - 'MYSQL_PASSWORD=password'
    ports:
      - '3308:3306'